services:
  app: &app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
      - .env.local
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?serverVersion=16&charset=utf8"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html:ro
    ports:
      - "${NGINX_PUBLIC_PORT:-8080}:80"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fx_tracker}
      POSTGRES_USER: ${POSTGRES_USER:-fx_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fx_pass}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-fx_tracker}", "-U", "${POSTGRES_USER:-fx_user}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "${DB_PUBLIC_PORT:-5435}:5432"
    restart: unless-stopped

  scheduler:
    <<: *app
    command: >
      sh -c "while true; do
        php bin/console app:rates:sync;
        sleep 60;
      done"
